name: Liam
favicon: null
layout_spectrum: 0.6689648861065507
typography_spectrum: 0.36990372254513204
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5453061659354717
  lightness: 0.9210698222741485
  saturation: 0.9751159807201475
  rhythmicContrast: 0.5392557389568537
purpose: []
